# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('m_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_edited_at', models.DateTimeField(auto_now=True, verbose_name='Last edited at')),
                ('like_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Like count')),
                ('dislike_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dislike count')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Rating')),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Comment count')),
                ('last_commented_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last commented at')),
                ('text', models.TextField(blank=True, verbose_name='Comment text')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('last_comment', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_comment+', to='m_comment.Comment', verbose_name='Last comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='m_profile.Profile', verbose_name='Comment from')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_include', to='m_comment.Comment', verbose_name='Comment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
