# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_comment', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_edited_at', models.DateTimeField(auto_now=True, verbose_name='Last edited at')),
                ('like_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Like count')),
                ('dislike_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dislike count')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Rating')),
                ('comment_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Comment count')),
                ('last_commented_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last commented at')),
                ('text', models.TextField(blank=True, verbose_name='Post text')),
                ('repost_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Repost count')),
                ('last_comment', models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_comment+', to='m_comment.Comment', verbose_name='Last comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='m_profile.Profile', verbose_name='Posted to')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted', to='m_profile.Profile', verbose_name='Sender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='By user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_include', to='m_post.Post', verbose_name='Post')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postinclude',
            unique_together=set([('message', 'content_type', 'object_id')]),
        ),
    ]
