# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is accepted')),
                ('accepted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Accepted at')),
                ('request_text', models.TextField(blank=True, verbose_name='Request text')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited_at', models.DateTimeField(auto_now=True, verbose_name='Last edited at')),
                ('like_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Like count')),
                ('dislike_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Dislike count')),
                ('rating', models.IntegerField(default=0, editable=False, verbose_name='Rating')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_profile.Profile')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=256, verbose_name='Community name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
            bases=('m_profile.profile', models.Model),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_profile.Profile')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('gender', models.BooleanField(default=True, verbose_name='Gender (male?)')),
                ('birthday', models.DateField(verbose_name='Birthday')),
            ],
            options={
                'abstract': False,
            },
            bases=('m_profile.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile owner'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='request_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request_sent', to='m_profile.Profile', verbose_name='Request from'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request', to='m_profile.Profile', verbose_name='Request to'),
        ),
        migrations.AlterIndexTogether(
            name='friendship',
            index_together=set([('request_to', 'is_active'), ('request_from', 'is_active')]),
        ),
    ]
