# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m_profile', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('invite_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_membership_invite', to='m_profile.Profile', verbose_name='Invite from')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_membership', to='m_profile.Profile', verbose_name='Invited profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Deleted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('text', models.TextField(blank=True, verbose_name='Message text')),
            ],
        ),
        migrations.CreateModel(
            name='MessageInclude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='include', to='m_chat.Message', verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_chat.Chat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('member_count', models.PositiveIntegerField(default=0, verbose_name='Member count')),
            ],
            bases=('m_chat.chat',),
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('chat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='m_chat.Chat')),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue1', to='m_profile.Profile', verbose_name='First person')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue2', to='m_profile.Profile', verbose_name='Second person')),
            ],
            bases=('m_chat.chat',),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='m_chat.Chat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='m_profile.Profile', verbose_name='Sender'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='Sender user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, db_index=False, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message+', to='m_chat.Message', verbose_name='Last message'),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('chat', 'created_at')]),
        ),
        migrations.AddField(
            model_name='conferencemembership',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='m_chat.Conference', verbose_name='Conference'),
        ),
        migrations.AddField(
            model_name='conference',
            name='members',
            field=models.ManyToManyField(related_name='conference', through='m_chat.ConferenceMembership', to='m_profile.Profile', verbose_name='Conference members'),
        ),
        migrations.AddField(
            model_name='conference',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_conference', to='m_profile.Profile', verbose_name='Conference owner'),
        ),
        migrations.AlterIndexTogether(
            name='conference',
            index_together=set([('owner', 'is_active')]),
        ),
    ]
